-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "StockMouvement" ADD COLUMN     "movement_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
